{% set name = "x3270" %}
{% set version = "4.1.10" %}
{% set sha256 = "8216572d0a14d4d18e65db97f6e2dd1aeb66eed02b4d544c79ed8d34ea54be71" %}

{% set ver_major_minor = ".".join(version.split(".")[:2]) %}
{% set ver_patch = version.split(".")[2] %}
{% set src_url_dir = "{:02d}.{:02d}".format(*(version.split(".") | map("int"))) %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  fn: {{ name|lower }}-{{ version }}.tar.gz
  url: http://x3270.bgp.nu/download/{{ src_url_dir }}/suite3270-{{ ver_major_minor }}ga{{ ver_patch }}-src.tgz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True    # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make        # [unix]
    - gnuconfig   # [unix]
  host:
    #- expat       # needed for `b3270`
    - libiconv    # [osx]
    - ncurses
    - openssl
    - readline
    - tk          # only really need the `tcl` bits

outputs:
  - name: {{ name }}-common
    files:
      - bin/pr3287
      - bin/x3270if
      - etc/x3270/ibm_hosts
    build:
      no_link:
        - etc/x3270/ibm_hosts
    requirements:
      build:
        - {{ compiler('c') }}
      host:
        - libiconv    # [osx]
        - ncurses
        - openssl
        - readline
    about:
      home: http://x3270.bgp.nu/
      license: BSD-3-Clause
      license_file: ws3270/LICENSE.txt
      summary: IBM 3270 terminal emulator shared files & utilities

  - name: c3270
    files:
      - bin/c3270
    requirements:
      build:
        - {{ compiler('c') }}
      host:
        - libiconv    # [osx]
        - ncurses
        - openssl
        - readline
      run:
        - {{ pin_subpackage(name + "-common", exact=True) }}
    about:
      home: http://x3270.bgp.nu/
      license: BSD-3-Clause
      license_file: ws3270/LICENSE.txt
      summary: IBM 3270 terminal emulator (character mode)

  - name: s3270
    files:
      - bin/s3270
      - bin/tcl3270
    requirements:
      build:
        - {{ compiler('c') }}
      host:
        - libiconv    # [osx]
        - openssl
        - tk
      run:
        - {{ pin_subpackage(name + "-common", exact=True) }}
    about:
      home: http://x3270.bgp.nu/
      license: BSD-3-Clause
      license_file: ws3270/LICENSE.txt
      summary: IBM 3270 terminal emulator screen scraping tools

about:
  home: http://x3270.bgp.nu/
  license: BSD-3-Clause
  license_family: BSD
  license_file: ws3270/LICENSE.txt
  doc_url: https://x3270.miraheze.org/wiki/Main_Page
  dev_url: https://sourceforge.net/projects/x3270/
  summary: Suite of IBM 3270 terminal emulators

extra:
  recipe-maintainers:
    - chenghlee
